version: '3.8'

services:
  postgres_db:
    image: postgres:15 # Use a specific, stable version of Postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: student_db
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data in a named volume

volumes:
  postgres_data:
